---
# create container
- hosts: localhost
  tasks:
    - name: Create nginx container.
      docker_container:
        name: docker-nginx
        image: centos:7
        command: /bin/bash
        tty: yes
        state: started

# provision
- hosts: docker-nginx
  connection: docker
  pre_tasks:
    - name: Add www user.
      user:
        name: www
        uid: 1000
        shell: /bin/sh
  roles:
    - role: shomatan.nginx
      nginx_user: www

# commit & finalize
- hosts: localhost
  tasks:
    - name: Commit nginx image.
      shell: docker commit docker-nginx shomatan/nginx:latest-centos7

    - name: Destory nginx container.
      docker_container:
        name: docker-nginx
        image: centos:7
        command: /bin/bash
        state: absent
